"""Added user_status column

Revision ID: 99275a4c2a9c
Revises: 
Create Date: 2025-08-20 16:53:16.617830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99275a4c2a9c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_status', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('user_status')

    # ### end Alembic commands ###
